// CLASSIC TEMPLATE
// Professional, trustworthy, traditional, elegant

interface TemplateData {
  business: string;
  tagline: string;
  description: string;
  services: string[];
  aboutText: string;
  phone: string;
  email: string;
  address: string;
  logoBase64: string | null;
  originalUrl: string;
  palette: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    backgroundAlt: string;
    text: string;
    textMuted: string;
  };
}

export function generateClassicTemplate(data: TemplateData): string {
  const {
    business,
    tagline,
    description,
    services,
    aboutText,
    phone,
    email,
    address,
    logoBase64,
    originalUrl,
    palette,
  } = data;

  const servicesHtml = services.slice(0, 6).map(service => `
              <div class="service-item">
                <span class="service-icon">✓</span>
                <span>${service}</span>
              </div>`).join('');

  const logoHtml = logoBase64
    ? `<img src="${logoBase64}" alt="${business}" class="logo-img" />`
    : `<span class="logo-text">${business}</span>`;

  return `---
// Generated by Garage Web - Classic Template
// Original: ${originalUrl}
// Generated: ${new Date().toISOString()}
export const prerender = true;
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${business}</title>
    <meta name="description" content="${description || tagline}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=Source+Sans+3:wght@300;400;500;600&display=swap" rel="stylesheet">
    <style>
      :root {
        --primary: ${palette.primary};
        --secondary: ${palette.secondary};
        --accent: ${palette.accent};
        --bg: ${palette.background};
        --bg-alt: ${palette.backgroundAlt};
        --text: ${palette.text};
        --text-muted: ${palette.textMuted};
      }

      * { margin: 0; padding: 0; box-sizing: border-box; }

      html { scroll-behavior: smooth; }

      body {
        font-family: 'Source Sans 3', -apple-system, sans-serif;
        background: var(--bg);
        color: var(--text);
        line-height: 1.7;
      }

      .container {
        max-width: 1140px;
        margin: 0 auto;
        padding: 0 24px;
      }

      h1, h2, h3, h4 {
        font-family: 'Libre Baskerville', Georgia, serif;
        font-weight: 400;
      }

      /* Top Bar */
      .top-bar {
        background: var(--secondary);
        color: white;
        padding: 10px 0;
        font-size: 13px;
      }

      .top-bar .container {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }

      .top-bar-contact {
        display: flex;
        gap: 24px;
      }

      .top-bar-contact a {
        color: rgba(255,255,255,0.8);
        text-decoration: none;
        display: flex;
        align-items: center;
        gap: 6px;
      }

      .top-bar-contact a:hover {
        color: white;
      }

      /* Navigation */
      nav {
        background: var(--bg);
        padding: 20px 0;
        border-bottom: 1px solid rgba(0,0,0,0.08);
        position: sticky;
        top: 0;
        z-index: 100;
      }

      nav .container {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }

      .logo {
        display: flex;
        align-items: center;
      }

      .logo-img {
        height: 50px;
        width: auto;
      }

      .logo-text {
        font-family: 'Libre Baskerville', serif;
        font-size: 24px;
        font-weight: 700;
        color: var(--secondary);
        letter-spacing: -0.5px;
      }

      .nav-links {
        display: flex;
        gap: 40px;
        list-style: none;
      }

      .nav-links a {
        color: var(--text);
        text-decoration: none;
        font-size: 15px;
        font-weight: 500;
        transition: color 0.2s;
        position: relative;
      }

      .nav-links a::after {
        content: '';
        position: absolute;
        bottom: -4px;
        left: 0;
        width: 0;
        height: 2px;
        background: var(--primary);
        transition: width 0.2s;
      }

      .nav-links a:hover::after {
        width: 100%;
      }

      .nav-cta {
        background: var(--primary);
        color: white;
        padding: 12px 28px;
        text-decoration: none;
        font-weight: 600;
        font-size: 14px;
        transition: all 0.2s;
        border-radius: 4px;
      }

      .nav-cta:hover {
        background: var(--secondary);
      }

      /* Hero */
      .hero {
        padding: 100px 0;
        background: linear-gradient(135deg, var(--bg-alt) 0%, var(--bg) 100%);
        position: relative;
        overflow: hidden;
      }

      .hero::before {
        content: '';
        position: absolute;
        top: 0;
        right: 0;
        width: 50%;
        height: 100%;
        background: var(--secondary);
        opacity: 0.03;
        clip-path: polygon(20% 0, 100% 0, 100% 100%, 0% 100%);
      }

      .hero-content {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 80px;
        align-items: center;
      }

      .hero-text h1 {
        font-size: clamp(36px, 4vw, 52px);
        line-height: 1.2;
        color: var(--secondary);
        margin-bottom: 24px;
      }

      .hero-text p {
        font-size: 18px;
        color: var(--text-muted);
        margin-bottom: 32px;
        line-height: 1.8;
      }

      .hero-buttons {
        display: flex;
        gap: 16px;
      }

      .btn-primary {
        background: var(--primary);
        color: white;
        padding: 16px 36px;
        text-decoration: none;
        font-weight: 600;
        font-size: 15px;
        transition: all 0.2s;
        border-radius: 4px;
        display: inline-flex;
        align-items: center;
        gap: 8px;
      }

      .btn-primary:hover {
        background: var(--secondary);
        transform: translateY(-2px);
      }

      .btn-outline {
        background: transparent;
        color: var(--secondary);
        padding: 16px 36px;
        text-decoration: none;
        font-weight: 600;
        font-size: 15px;
        border: 2px solid var(--secondary);
        border-radius: 4px;
        transition: all 0.2s;
      }

      .btn-outline:hover {
        background: var(--secondary);
        color: white;
      }

      .hero-features {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 24px;
      }

      .hero-feature {
        background: white;
        padding: 28px;
        border-radius: 8px;
        box-shadow: 0 4px 20px rgba(0,0,0,0.06);
        border-left: 4px solid var(--primary);
      }

      .hero-feature-icon {
        font-size: 32px;
        margin-bottom: 12px;
      }

      .hero-feature h3 {
        font-size: 18px;
        margin-bottom: 8px;
        color: var(--secondary);
      }

      .hero-feature p {
        font-size: 14px;
        color: var(--text-muted);
        line-height: 1.6;
      }

      /* Services */
      .services {
        padding: 100px 0;
      }

      .section-header {
        text-align: center;
        margin-bottom: 60px;
      }

      .section-subtitle {
        color: var(--primary);
        font-size: 13px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 2px;
        margin-bottom: 12px;
      }

      .section-header h2 {
        font-size: clamp(32px, 4vw, 44px);
        color: var(--secondary);
        margin-bottom: 16px;
      }

      .section-header p {
        color: var(--text-muted);
        font-size: 18px;
        max-width: 600px;
        margin: 0 auto;
      }

      .services-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 16px;
        max-width: 800px;
        margin: 0 auto;
      }

      .service-item {
        display: flex;
        align-items: center;
        gap: 12px;
        padding: 20px 24px;
        background: var(--bg-alt);
        border-radius: 8px;
        font-size: 16px;
        font-weight: 500;
        transition: all 0.2s;
      }

      .service-item:hover {
        background: white;
        box-shadow: 0 4px 20px rgba(0,0,0,0.08);
        transform: translateY(-2px);
      }

      .service-icon {
        color: var(--primary);
        font-weight: bold;
      }

      /* About */
      .about {
        padding: 100px 0;
        background: var(--secondary);
        color: white;
      }

      .about-content {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 80px;
        align-items: center;
      }

      .about-text .section-subtitle {
        color: var(--accent);
      }

      .about-text h2 {
        font-size: clamp(32px, 4vw, 44px);
        margin-bottom: 24px;
        color: white;
      }

      .about-text p {
        font-size: 17px;
        line-height: 1.9;
        color: rgba(255,255,255,0.8);
        margin-bottom: 32px;
      }

      .about-stats {
        display: flex;
        gap: 48px;
      }

      .stat {
        text-align: center;
      }

      .stat-value {
        font-family: 'Libre Baskerville', serif;
        font-size: 48px;
        color: var(--accent);
        line-height: 1;
      }

      .stat-label {
        font-size: 14px;
        color: rgba(255,255,255,0.6);
        margin-top: 8px;
      }

      .about-image {
        background: rgba(255,255,255,0.1);
        border-radius: 8px;
        height: 400px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 100px;
      }

      /* Contact */
      .contact {
        padding: 100px 0;
      }

      .contact-content {
        display: grid;
        grid-template-columns: 1fr 1.2fr;
        gap: 80px;
      }

      .contact-info h2 {
        font-size: clamp(32px, 4vw, 44px);
        color: var(--secondary);
        margin-bottom: 16px;
      }

      .contact-info > p {
        color: var(--text-muted);
        font-size: 17px;
        margin-bottom: 40px;
        line-height: 1.8;
      }

      .contact-details {
        display: flex;
        flex-direction: column;
        gap: 24px;
      }

      .contact-item {
        display: flex;
        gap: 16px;
      }

      .contact-icon {
        width: 48px;
        height: 48px;
        background: var(--bg-alt);
        border-radius: 8px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 20px;
        flex-shrink: 0;
      }

      .contact-content-inner {
        padding-top: 4px;
      }

      .contact-label {
        font-size: 12px;
        color: var(--text-muted);
        text-transform: uppercase;
        letter-spacing: 1px;
        margin-bottom: 4px;
      }

      .contact-value {
        font-size: 17px;
        font-weight: 500;
        color: var(--secondary);
      }

      .contact-form {
        background: var(--bg-alt);
        padding: 48px;
        border-radius: 12px;
      }

      .contact-form h3 {
        font-size: 24px;
        color: var(--secondary);
        margin-bottom: 24px;
      }

      .form-row {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 16px;
        margin-bottom: 16px;
      }

      .form-group {
        margin-bottom: 16px;
      }

      .form-label {
        display: block;
        font-size: 14px;
        font-weight: 500;
        margin-bottom: 8px;
        color: var(--text);
      }

      .form-input {
        width: 100%;
        padding: 14px 16px;
        border: 1px solid rgba(0,0,0,0.1);
        border-radius: 6px;
        font-size: 15px;
        font-family: inherit;
        background: white;
        transition: border-color 0.2s;
      }

      .form-input:focus {
        outline: none;
        border-color: var(--primary);
      }

      .form-textarea {
        min-height: 120px;
        resize: vertical;
      }

      .form-submit {
        width: 100%;
        padding: 16px;
        background: var(--primary);
        color: white;
        border: none;
        border-radius: 6px;
        font-size: 15px;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.2s;
      }

      .form-submit:hover {
        background: var(--secondary);
      }

      /* Footer */
      footer {
        background: var(--secondary);
        color: white;
        padding: 60px 0 30px;
      }

      .footer-content {
        display: grid;
        grid-template-columns: 2fr 1fr 1fr 1fr;
        gap: 48px;
        margin-bottom: 48px;
      }

      .footer-brand .logo-text {
        color: white;
        margin-bottom: 16px;
        display: block;
      }

      .footer-brand p {
        color: rgba(255,255,255,0.6);
        font-size: 14px;
        line-height: 1.7;
      }

      .footer-col h4 {
        font-size: 16px;
        margin-bottom: 20px;
        color: white;
      }

      .footer-col ul {
        list-style: none;
      }

      .footer-col li {
        margin-bottom: 10px;
      }

      .footer-col a {
        color: rgba(255,255,255,0.6);
        text-decoration: none;
        font-size: 14px;
        transition: color 0.2s;
      }

      .footer-col a:hover {
        color: white;
      }

      .footer-bottom {
        padding-top: 24px;
        border-top: 1px solid rgba(255,255,255,0.1);
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 13px;
        color: rgba(255,255,255,0.5);
      }

      .footer-bottom a {
        color: var(--accent);
        text-decoration: none;
      }

      /* Countdown */
      .countdown-banner {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        background: var(--primary);
        color: white;
        padding: 14px 24px;
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 20px;
        font-size: 14px;
        z-index: 100;
      }

      .countdown-timer {
        font-family: monospace;
        font-size: 18px;
        font-weight: 600;
      }

      .countdown-btn {
        background: white;
        color: var(--primary);
        padding: 10px 24px;
        border-radius: 4px;
        text-decoration: none;
        font-weight: 600;
        font-size: 13px;
        transition: transform 0.2s;
      }

      .countdown-btn:hover {
        transform: scale(1.02);
      }

      /* Responsive */
      @media (max-width: 968px) {
        .top-bar { display: none; }
        .nav-links { display: none; }
        .hero-content, .about-content, .contact-content {
          grid-template-columns: 1fr;
          gap: 48px;
        }
        .hero-features { margin-top: 48px; }
        .footer-content {
          grid-template-columns: 1fr 1fr;
          gap: 32px;
        }
        .form-row { grid-template-columns: 1fr; }
      }

      @media (max-width: 600px) {
        .services-grid { grid-template-columns: 1fr; }
        .footer-content { grid-template-columns: 1fr; }
        .about-stats { flex-direction: column; gap: 24px; }
      }
    </style>
  </head>
  <body>
    <div class="top-bar">
      <div class="container">
        <div class="top-bar-contact">
          ${phone ? `<a href="tel:${phone}">📞 ${phone}</a>` : ''}
          ${email ? `<a href="mailto:${email}">✉️ ${email}</a>` : ''}
        </div>
        <div>Trusted by hundreds of clients</div>
      </div>
    </div>

    <nav>
      <div class="container">
        <a href="#" class="logo">
          ${logoHtml}
        </a>
        <ul class="nav-links">
          <li><a href="#services">Services</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        <a href="#contact" class="nav-cta">Free Consultation</a>
      </div>
    </nav>

    <section class="hero">
      <div class="container">
        <div class="hero-content">
          <div class="hero-text">
            <h1>${tagline || `Welcome to ${business}`}</h1>
            <p>${description || 'We provide professional services with integrity, expertise, and a commitment to your success. Trust our experienced team to deliver results.'}</p>
            <div class="hero-buttons">
              <a href="#contact" class="btn-primary">Get Started →</a>
              <a href="#services" class="btn-outline">Our Services</a>
            </div>
          </div>
          <div class="hero-features">
            <div class="hero-feature">
              <div class="hero-feature-icon">🏆</div>
              <h3>Experienced Team</h3>
              <p>Decades of combined expertise at your service</p>
            </div>
            <div class="hero-feature">
              <div class="hero-feature-icon">🤝</div>
              <h3>Client Focused</h3>
              <p>Your success is our top priority</p>
            </div>
            <div class="hero-feature">
              <div class="hero-feature-icon">✓</div>
              <h3>Proven Results</h3>
              <p>Track record of excellence</p>
            </div>
            <div class="hero-feature">
              <div class="hero-feature-icon">⚡</div>
              <h3>Responsive Service</h3>
              <p>Always here when you need us</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="services" id="services">
      <div class="container">
        <div class="section-header">
          <div class="section-subtitle">Our Expertise</div>
          <h2>Services We Offer</h2>
          <p>Comprehensive solutions tailored to your unique needs</p>
        </div>
        <div class="services-grid">
          ${servicesHtml}
        </div>
      </div>
    </section>

    <section class="about" id="about">
      <div class="container">
        <div class="about-content">
          <div class="about-text">
            <div class="section-subtitle">About Us</div>
            <h2>Why Choose ${business}?</h2>
            <p>${aboutText || 'With a foundation built on trust, expertise, and unwavering commitment to our clients, we have established ourselves as a leader in our field. Our team brings together years of experience and a passion for excellence.'}</p>
            <div class="about-stats">
              <div class="stat">
                <div class="stat-value">15+</div>
                <div class="stat-label">Years Experience</div>
              </div>
              <div class="stat">
                <div class="stat-value">500+</div>
                <div class="stat-label">Happy Clients</div>
              </div>
              <div class="stat">
                <div class="stat-value">98%</div>
                <div class="stat-label">Success Rate</div>
              </div>
            </div>
          </div>
          <div class="about-image">⚖️</div>
        </div>
      </div>
    </section>

    <section class="contact" id="contact">
      <div class="container">
        <div class="contact-content">
          <div class="contact-info">
            <div class="section-subtitle">Contact Us</div>
            <h2>Get in Touch</h2>
            <p>We're here to help. Reach out for a free consultation and let's discuss how we can assist you.</p>

            <div class="contact-details">
              ${phone ? `
              <div class="contact-item">
                <div class="contact-icon">📞</div>
                <div class="contact-content-inner">
                  <div class="contact-label">Phone</div>
                  <div class="contact-value">${phone}</div>
                </div>
              </div>
              ` : ''}

              ${email ? `
              <div class="contact-item">
                <div class="contact-icon">✉️</div>
                <div class="contact-content-inner">
                  <div class="contact-label">Email</div>
                  <div class="contact-value">${email}</div>
                </div>
              </div>
              ` : ''}

              ${address ? `
              <div class="contact-item">
                <div class="contact-icon">📍</div>
                <div class="contact-content-inner">
                  <div class="contact-label">Address</div>
                  <div class="contact-value">${address}</div>
                </div>
              </div>
              ` : ''}
            </div>
          </div>

          <div class="contact-form">
            <h3>Send Us a Message</h3>
            <form>
              <div class="form-row">
                <div class="form-group">
                  <label class="form-label">First Name</label>
                  <input type="text" class="form-input" placeholder="John">
                </div>
                <div class="form-group">
                  <label class="form-label">Last Name</label>
                  <input type="text" class="form-input" placeholder="Smith">
                </div>
              </div>
              <div class="form-group">
                <label class="form-label">Email</label>
                <input type="email" class="form-input" placeholder="john@example.com">
              </div>
              <div class="form-group">
                <label class="form-label">How Can We Help?</label>
                <textarea class="form-input form-textarea" placeholder="Tell us about your situation..."></textarea>
              </div>
              <button type="submit" class="form-submit">Submit Inquiry</button>
            </form>
          </div>
        </div>
      </div>
    </section>

    <footer>
      <div class="container">
        <div class="footer-content">
          <div class="footer-brand">
            <span class="logo-text">${business}</span>
            <p>Professional services you can trust. We're committed to your success and satisfaction.</p>
          </div>
          <div class="footer-col">
            <h4>Quick Links</h4>
            <ul>
              <li><a href="#services">Services</a></li>
              <li><a href="#about">About Us</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div>
          <div class="footer-col">
            <h4>Contact</h4>
            <ul>
              ${phone ? `<li><a href="tel:${phone}">${phone}</a></li>` : ''}
              ${email ? `<li><a href="mailto:${email}">${email}</a></li>` : ''}
            </ul>
          </div>
          <div class="footer-col">
            <h4>Hours</h4>
            <ul>
              <li>Mon - Fri: 9am - 5pm</li>
              <li>Sat: By Appointment</li>
              <li>Sun: Closed</li>
            </ul>
          </div>
        </div>
        <div class="footer-bottom">
          <div>© ${new Date().getFullYear()} ${business}. All rights reserved.</div>
          <div>Redesigned by <a href="https://garage.co.nz">Garage</a></div>
        </div>
      </div>
    </footer>

    <div class="countdown-banner">
      <span>This preview expires in</span>
      <span class="countdown-timer" id="countdown">48:00:00</span>
      <a href="#contact" class="countdown-btn">I Want This Site</a>
    </div>

    <script>
      const deadline = new Date(Date.now() + 48 * 60 * 60 * 1000);
      function updateCountdown() {
        const diff = deadline - new Date();
        if (diff <= 0) { document.getElementById('countdown').textContent = 'EXPIRED'; return; }
        const h = Math.floor(diff / 3600000);
        const m = Math.floor((diff % 3600000) / 60000);
        const s = Math.floor((diff % 60000) / 1000);
        document.getElementById('countdown').textContent =
          h.toString().padStart(2,'0')+':'+m.toString().padStart(2,'0')+':'+s.toString().padStart(2,'0');
      }
      updateCountdown();
      setInterval(updateCountdown, 1000);
    </script>
  </body>
</html>
`;
}
